### ISSUE TITLE
Đăng ký

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#1]
Giao diện:
+ Ở các giao diện thì sẽ có link "Đăng ký" ở trên cùng bên phải giao diện, bên phải link "Đăng nhập"
+ Logo ở trên cùng bên trái giao diện
+ Title "Đăng ký" ở trên cùng ở giữa giao diện
+ bên dưới Title có textbox dành cho email và label nằm bên  trên textbox 
+ bên dưới Email có textbox dành cho Username và label nằm bên  trên textbox 
+ bên dưới Username có textbox dành cho Password và label nằm bên  trên textbox
+ bên dưới Password có textbox dành cho Verify Password và label nằm bên  trên textbox
+ bên dưới Verify Password có textbox dành cho Phone và label nằm bên  trên textbox
+ bên dưới Phone có textbox dành cho Date và label nằm bên  trên textbox
+ bên dưới Date  có textbox dành cho DiaChi và label nằm bên  trên textbox
+ Dưới cùng sẽ có button dành cho "Đăng Ký"

Xử lý:
+ Người dùng ấn vào link "Đăng ký" ở các giao diện 
+ Khi user nhập đủ thông tin và ấn button "Đăng Ký" thì hệ thống sẽ kiểm tra thông tin bên trong textbox có hợp lệ hay không thì sẽ lưu thông tin vào database
+ Khi kiểm tra không trùng verify password thì hệ thống báo lỗi:"Vui lòng nhập lại password!"
+ Khi email đã được dùng thì hệ thống báo lỗi:"Email đã được sử dụng!"
+ Khi nhập password không đúng theo quy định hệ thống báo lỗi:"Password phải chứa ít nhất 1 ký tự viết hoa và ít nhất 6 chữ số theo sau"
+ Khi sai username hoặc đã được sử dụng:"Username đã được sử dụng"
+ Username chứa kí tự đặc biệt: "Username không được chứa kí tự đặc biệt"

Lưu trữ: 
+ Khi người dùng ấn "Đăng Ký" thì hệ thống sẽ lưu Email, Username, Password vào database

**Comment by Dohuuphi** [comment]
Tôi đã nhận và đang thực hiện.

**Comment by Dohuuphi** [comment]
đã hoàn thành.
