### ISSUE TITLE
Cập nhật thông tin trong chi tiết tour

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#10]
Cập nhật thông tin trong chi tiết tour
-Giao diện: gồm 3 thành phần chính
 Thành phần 1:
         + Có tiêu đề "Cập nhật tour" ở đầu trang
Thành phần 2: chứa các trường thông tin tour nằm ở giữa trang gồm
         + bên phải ảnh tour có tên tour
         + dưới tên tour có giá tour
         + dưới giá tour có nội dung chi tiết tour
         + dưới chi tiết tour có ngày khởi hành
Thành phần 3:
         + dưới cùng có 2 button "Lưu" và "Hủy" và 1 link "Quay lại"
-Xử lý:
 + Khi ấn "Lưu" hệ thống sẽ Kiểm tra các trường thông tin 
 + Khi ấn "Hủy" hệ thống sẽ trở về giao diện danh sách tour
 + Khi lỗi trường thông tin hệ thống sẽ thông báo và yêu cầu nhập lại
-Lưu trữ:
+ Khi các trường thông tin không có lỗi thì dữ liệu sẽ được ghi vào csdl.

**Comment by phuit30s** [comment]
Đang thực hiện
