### ISSUE TITLE
Cập nhật thông tin trong danh sách tour

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#11]
Cập nhật thông tin trong danh sách tour
-Giao diện:
 +Trong danh sách tour có button "Cập nhật danh sách tour" ở trên cùng bên phải ảnh  trong danh sách tour, khi ấn vào hệ thống sẽ chuyễn sang giao diện cập nhật danh sách tour
+ dưới header có list ảnh tour ở bên trái (Col 4)
 + bên phải ảnh tour có tên tour
 + dưới tên tour có giá tour
 + dưới cùng có 2 button "Chấp nhận" và "Cancel" và 1 link "back to list tour"
-Xử lý:
 + Khi ấn "Chấp nhận" hệ thống sẽ Kiểm tra tên tour để chấp nhận thay đổi chi tiết tour hay không
 + Khi ấn "Cancel" hệ thống sẽ trở về giao diện list tour
 + Khi lỗi tên hoặc trùng tên: "vui lòng chọn tên khác!"
-Lưu trữ:
+ Khi button "Chấp nhận" được ấn thành công thì hệ thống sẽ lưu trữ tên tour, giá tour

**Comment by NguyenDucTinNew** [comment]
đã nhận

**Comment by NguyenDucTinNew** [comment]
đã hoàn thành
