### ISSUE TITLE
Hiển thị giao diện trang chủ

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#12]
Giao diện:
 + Có logo ở trên cùng bên trái giao diện
 + Thanh tìm kiếm ở trên cùng ở giữa
 + Có logo tài khoản ở trên cùng bên phải giao diện(nếu đã đăng nhập) hoặc có 2 link "Đăng nhập" và "Đăng ký"
 + Trên logo tài khoản có image tim nhỏ cho mục "Yêu thích" và image giỏ hàng cho trang giỏ hàng
 + navbar với vài link dẫn sang các trang phụ
 + dưới navbar hiển thị thông tin cơ bản về web
 + dưới cùng có footer hiển thị các link theo dạng cột (3 cột) với các thông tin web và trợ giúp
Xử lý:
+ Trên Navbar khi ấn vào navlink sẽ hiển thị các trang tưởng ứng

**Comment by HuyLieu1603** [comment]
đã nhận
