### ISSUE TITLE
Xem danh sách khách hàng từ tour

### ISSUE THREAD

**Issue by PHILONG2212** [phong0072012/DoAnCNPM#26]
Xem danh sách khách hàng từ tour
Giao diện:
+ Trong mỗi item của list tour có button "Xem khách hàng đã đặt tour" dưới ảnh tour
+ Trên cùng giao diện có title "Danh sách khách hàng"
+ Dưới title có tên tour nằm bên trái
+ Dưới tên tour có ngày khởi hành
+ Dưới ngày khởi hành có list danh sách khách hàng thể hiện theo dạng lưới
+ bên phải Trên cùng của list có button "Thêm khách hàng"
+ Mỗi item trong list có Tên khách hàng
+ Dưới tên khách hàng có số lượng vé đã đặt
+ Dưới số lượng vé có ngày đặt
+ Dưới ngày đặt có tình trạng thanh toán (Có 2 trạng thái là "Đã thanh toán" hoặc "Chưa thanh toán")
+ Bên phải item có button "Xóa khách hàng"
+ Dưới cùng có link "Quay lại danh sách tour"

**Comment by Dohuuphi** [comment]
đã nhận

**Comment by HuyLieu1603** [comment]
Đã nhận

**Comment by HuyLieu1603** [comment]
Đã hoàn thành
