### ISSUE TITLE
Xem danh sách xác nhận các đơn đặt chỗ

### ISSUE THREAD

**Issue by NguyenDucTinNew** [phong0072012/DoAnCNPM#31]
Giao diện:
+ Ở trên cùng ở giữa có title "Danh sách xác nhận đơn đặt"
+ Ở dưới có list danh sách khách hàng đã đặt đơn
+ Mỗi item trong list có tên khách hàng nằm ở trên cùng
+ Dưới tên khách hàng có số lượng vé đặt
+ Dưới số lượng vé có tên tour
+ Dưới tên tour có Id Tour
+ bên phải item có button "Xác nhận"

**Comment by NguyenDucTinNew** [comment]
đã nhận

**Comment by HuyLieu1603** [comment]
Đã nhận

**Comment by HuyLieu1603** [comment]
Đã hoàn thành
