### ISSUE TITLE
Đăng nhập

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#4]
Giao diện:
+Ở các giao diện thì sẽ có link "Đăng nhập" ở trên cùng bên phải giao diện, bên trái link "Đăng ký"
+ Logo ở trên cùng bên trái giao diện
+ Title "Đăng nhập" ở trên cùng ở giữa giao diện
+ bên dưới Email có textbox dành cho Username và label nằm bên trên textbox 
+ bên dưới Username có textbox dành cho Password và label nằm bên trên textbox 
+ Dưới cùng sẽ có button  ở giữa dành cho "Sign in"
+Người dùng ấn vào link "Đăng ký" ở giao diện 
+ Khi user nhập đủ thông tin và ấn button "Sign in" thì hệ thống sẽ bắt đầu load database account để kiểm tra thông tin bên trong textbox có hợp lệ so với database hay không
+ Người dùng ấn button "Cancel" thì hệ thống sẽ chuyển người dùng về lại trang giao diện chính
+ Khi người dùng sai Username hoặc password: "Username hoặc password không đúng!"
+Username không tồn tại: "Username không tồn tại!"
Lưu trữ: 
Khi người dùng ấn "Sign in" thì hệ thống sẽ lưu Username, Password vào database

**Comment by Dohuuphi** [comment]
Tôi đã nhận và đang thực hiện

**Comment by Dohuuphi** [comment]
đã hoàn thành.

**Comment by HuyLieu1603** [comment]
đã nhận

**Comment by HuyLieu1603** [comment]
đã hoàn thành
