### ISSUE TITLE
Chỉnh sữa tour

### ISSUE THREAD

**Issue by PHILONG2212** [phong0072012/DoAnCNPM#66]
Giao diện: chứa các trường thông tin tour nằm ở giữa trang gồm
•	Tên
•	Giá
•	Ảnh
•	Ngày khởi hành
•	Nội dung mô tả (Null)
•	Loại Tour (Null)
•	Khuyến mãi (Null)
•	Dưới cùng có 2 button dành cho "Lưu" và "Cancel" và 1 link "Quay lại danh sách"
Xử lý:
•	Khi ấn "Lưu" hệ thống sẽ Kiểm tra các trường thông tin
•	Khi ấn "Hủy" hệ thống sẽ trở về giao diện danh sách tour
•	Khi lỗi trường thông tin hệ thống sẽ thông báo và yêu cầu nhập lại
Lưu trữ:
•	Khi các trường thông tin không có lỗi thì dữ liệu sẽ được ghi vào csdl.

**Comment by HuyLieu1603** [comment]
đã nhận

**Comment by HuyLieu1603** [comment]
đã hoàn thành
