### ISSUE TITLE
Xóa tour

### ISSUE THREAD

**Issue by phong0072012** [phong0072012/DoAnCNPM#7]
Xóa tour
Giao diện:
+ Ở giao diện index sẽ có link "delete" ở bên phải mỗi tour trong giao diện "Index", ấn vào hệ thống sẽ chuyển sang giao diện xóa tour
+ Ở trên cùng ở giữa có title "delete"
+ Ở dưới title có label dành cho "ID tour" và label nội dung nằm ở bên phải
+ Ở dưới "id tour" có label dành cho "tên tour" và label nội dung nằm ở bên phải
+ Ở dưới "tên tour" có label dành cho "giá tour" và label nội dung nằm ở bên phải
+ Ở dưới "giá tour" có label dành cho "ảnh tour" và label nội dung nằm ở bên phải
+ Ở dưới "ảnh tour" có label dành cho "ngày khởi hành" và label nội dung nằm ở bên phải
+ Ở dưới "ngày khởi hành" có label dành cho "nội dung tour" và label nội dung nằm ở bên phải
+Dưới cùng có 1 button dành cho "Thêm tour mới" và 1 link "Quay lại danh sách"
Xử lý:
+Ấn vào button "Xóa" hệ thống sẽ cảnh báo :"Bạn có chắc chắn muốn xóa?"
+ Khi ấn vào link "Quay lại danh sách" thì hệ thống sẽ hiện giao diện "Index"
+ Nếu có khách hàng đặt tour đó rồi thì hệ thống sẽ báo: "Tour này đang có khách hàng đặt vé"
Lưu trữ:
Button "Xóa" được ấn thành công, hệ thống sẽ tiến hành xóa tất cả thông tin của tour đó trong database

**Comment by HuyLieu1603** [comment]
`public ActionResult Xoa(int id)
        {
            Tour tour = db.tours.Where(row => row.MaTour == id).FirstOrDefault();
            return View(tour);
        }

        [HttpPost]
        public ActionResult Xoa(int id, Tour p)
        {
            Tour tour = db.tours.Where(row => row.MaTour == id).FirstOrDefault();
            db.tours.Remove(tour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }`

**Comment by HuyLieu1603** [comment]
đã nhận

**Comment by HuyLieu1603** [comment]
public ActionResult Xoa(int id)
        {
            TourNuocNgoai tour = db.TourNuocNgoais.Where(row => row.MaTourNuocNgoai == id).FirstOrDefault();
            return View(tour);
        }

        [HttpPost]
        public ActionResult Xoa(int id, TourNuocNgoai p)
        {
            TourNuocNgoai tour = db.TourNuocNgoais.Where(row => row.MaTourNuocNgoai == id).FirstOrDefault();
            db.TourNuocNgoais.Remove(tour);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

**Comment by HuyLieu1603** [comment]
đã hoàn thành
